METRICS:
  Gauge:
    - metric: temperature
      key: module_temperature
      type: celsius
      description: Port SFP temperature
      function: floatify

    - metric: sending_laser_fault_alarm
      key: tx_laser_fault_alarm
      description: Port tx laser fault alarm on sfp (0(FAULT)/1(OK))
      function: is_ok

    - metric: sending_optic_power
      key: tx_optic_power
      description: Sending Power on interface
      type: dbm
      function: floatify

    - metric: receiving_optic_power
      key: rx_optic_power
      description: Receiving Power on interface
      type: dbm
      function: floatify

    - metric: voltage
      key: module_voltage
      description: Port SFP voltage
      type: dbm
      function: none_to_zero

    - metric: laser_bias_current
      key: laser_bias_current
      description: Laser Bias Current
      type: dbm
      function: floatify
  # Thresholds for alarms
  # temperature
    - metric: module_temperature_high_alarm_threshold
      key: module_temperature_high_alarm
      description: Threshold for alarms
      type: celsius
      function: none_to_plus_inf

    - metric: module_temperature_low_alarm_threshold
      key: module_temperature_low_alarm
      description: Threshold for alarms
      type: celsius
      function: none_to_minus_inf

    - metric: module_temperature_high_warn_threshold
      key: module_temperature_high_warn
      description: Threshold for alarms
      type: celsius
      function: none_to_plus_inf

    - metric: module_temperature_low_warn_threshold
      key: module_temperature_low_warn
      description: Threshold for alarms
      type: celsius
      function: none_to_minus_inf
  # receiving
    - metric: receiving_optic_power_high_alarm_threshold
      key: rx_optic_power_high_alarm
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: receiving_optic_power_low_alarm_threshold
      key: rx_optic_power_low_alarm
      description: Threshold for alarms
      type: 
      function: floatify

    - metric: receiving_optic_power_high_warn_threshold
      key: rx_optic_power_high_warn
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: receiving_optic_power_low_warn_threshold
      key: rx_optic_power_low_warn
      description: Threshold for alarms
      type: dbm
      function: floatify
  # sending
    - metric: sending_optic_power_high_alarm_threshold
      key: tx_optic_power_high_alarm
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: sending_optic_power_low_alarm_threshold
      key: tx_optic_power_low_alarm
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: sending_optic_power_high_warn_threshold
      key: tx_optic_power_high_warn
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: sending_optic_power_low_warn_threshold
      key: tx_optic_power_low_warn
      description: Threshold for alarms
      type: dbm
      function: floatify

  # laser bias
    - metric: laser_bias_high_alarm_threshold
      key: laser_bias_high_alarm
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: laser_bias_low_alarm_threshold
      key: laser_bias_low_alarm
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: laser_bias_high_warn_threshold
      key: laser_bias_high_warn
      description: Threshold for alarms
      type: dbm
      function: floatify

    - metric: laser_bias_low_warn_threshold
      key: laser_bias_low_warn
      description: Threshold for alarms
      type: dbm
      function: floatify

LABELS:
  - label: description
    key: description

  - label: MAC
    key: macaddr

  - label: speed
    key: speed

  - label: interface
    key: interface_name