RoutingEngineTable:
  rpc: get-route-engine-information
  args:
  item: route-engine | multi-routing-engine-item
  key:
    - slot
    - model
    - re-name
  view: RoutingEngineView

RoutingEngineView:
  fields:
    model: model | route-engine-information/route-engine/model
    last_reboot_reason: last_reboot_reason | route-engine-information/route-engine/last-reboot-reason
    uptime: { up-time/@seconds | route-engine-information/route-engine/up-time/@seconds: int }
    cpu_idle: { cpu-idle | route-engine-information/route-engine/cpu-idle: int }
    memory_dram_size: memory-dram-size | route-engine-information/route-engine/memory-system-total
    memory_buffer_utilization: { memory-buffer-utilization | route-engine-information/route-engine/memory-system-total-util: int }

SoftwareTable:
  rpc: get-software-information
  args:
  item: multi-routing-engine-item
  key: re-name
  view: SoftwareView

SoftwareView:
  fields:
    hostname: software-information/host-name
    model: software-information/product-model
    version: software-information/junos-version


EnvironmentTable:
  rpc: get-environment-information
  args:
  item: environment-item
  key: name
  view: EnvironmentView

EnvironmentView:
  fields:
    class: class
    status: status
    temperature: { temperature/@celsius: int }